### ISSUE TITLE
SMILES isomeric/canonical

### ISSUE THREAD

**Issue by Adafede** [bjonnh/npwd_importer#10]
Checking quickly some entries (see [Q77564406](https://www.wikidata.org/wiki/Q77564406) for example or [Q19414 ](https://www.wikidata.org/wiki/Q19414) (it is the example for canonical SMILES [page](https://www.wikidata.org/wiki/Property:P233)  we updated wrongly :D), it seems that we should update the rule for isomeric/canonical SMILES assignment.

From what I understood, we should state:

- **isomeric** when the whole stereochemistry is defined **AND** stereocenters >0. (I should then quickly update the script to keep that info, thanks @oolonek for outputting it since the beginning!)

- **canonical** when the stereochemistry is not fully defined **OR** stereocenters <1. However, I can not tell if a half defined stereochemistry SMILES is still considered OK for that property, we should maybe ping the WD chemistry people...

P.S.: I think it should be ok, see [Q64940745 ](https://www.wikidata.org/wiki/Q64940745) or [Q102338681](https://www.wikidata.org/wiki/Q102338681)

**Comment by Adafede** [comment]
See also https://www.wikidata.org/wiki/Q4817643 to think how to handle multiple canonical SMILES?

**Comment by oolonek** [comment]
.... maybe it should be classified as isomeric SMILES **as soon as** it as at least one defined stereocenter (or double bond). The two values we have are stereocenters_count and undefined_stereocenters_count. In this case it would be :

- isomeric SMILES when stereocenters_count != undefined_stereocenters_count
- canonical SMILES when stereocenters_count == undefined_stereocenters_count

**Comment by Adafede** [comment]
Upvote your proposal, mine was wrong
